### ISSUE TITLE
Fix deploy script

### ISSUE THREAD

**Issue by tomwayson** [Esri/ember-arcgis-server-services#30]
`npm run deploy` tries to deploy using gh-pages, but really the app's on surge.

I tried `ember surge`, but I get this:

```bash
    Login to surge.sh!

    Surge - surge.sh

              token: *****************
       project path: dist
               size: 10 files, 763.0 KB
             domain: ember-arcgis-server-services.surge.sh


    Aborted - you do not have permission to publish to ember-arcgis-server-services.surge.sh
```

@dbouwman can you add me to that and then I'll deploy the latest and update the npm script.

**Comment by dbouwman** [comment]
@tomwayson There are npm scripts for each...
https://github.com/Esri/ember-arcgis-portal-services/blob/master/package.json#L24-L26

TBH - I'm not sure how to add you to each of them... I'm kinda doing some janky stuff w/ surge
anyhow - I'll just deploy them

You do have access to deploy to `eapsqa.surge.sh` though
