### ISSUE TITLE
BUG: serverInfo.owningSystemUrl may be undefined

### ISSUE THREAD

**Issue by dbouwman** [Esri/ember-arcgis-server-services#48]
Older servers may return `serverInfo` but not have `.owningSystemUrl` defined, which causes the `shouldAddToken` fn to throw.

i.e. http://maps.slcgov.com/mapservice/rest/info?f=json

returns 
```json
{
"currentVersion": 10.1,
"fullVersion": "10.1",
"soapUrl": "http://maps.slcgov.com/mapservice/services",
"secureSoapUrl": "https://maps.slcgov.com/mapservice/services",
"authInfo": {
"isTokenBasedSecurity": true,
"tokenServicesUrl": "https://maps.slcgov.com/mapservice/tokens/",
"shortLivedTokenValidity": 60
}
}
```

In this case, I think we should simply not send tokens

**Comment by jgravois** [comment]
i'm pretty sure `owningSystemUrl` is evidence that the instance of ArcGIS Server is [federated with Portal](http://enterprise.arcgis.com/en/portal/latest/administer/linux/federate-an-arcgis-server-site-with-your-portal.htm).

i agree that in this situation its the right move to skip sending tokens.

> fyi: i pitched a tweak to rest-js to add support for non-federated UserSessions in https://github.com/Esri/arcgis-rest-js/pull/423
